---
title: "Setting up website"
author: "Jessica Cooperstone"
date: "4/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Really good resources here:

* [blogdown: Creating website with R Markdown](https://bookdown.org/yihui/blogdown/)
* [blogdown reference manual](https://cran.r-project.org/web/packages/blogdown/blogdown.pdf)
* [blogdown github](https://github.com/rstudio/blogdown)
* [Up and running with blogdown in 2021](https://alison.rbind.io/post/new-year-new-blogdown/#) by Alison Presmanes Hill

# 1 Create repo

# 2 Creating project
```{r}
if (!requireNamespace("remotes")) install.packages("remotes")
remotes::install_github("rstudio/blogdown")
```

```{r}
library(blogdown)

# set up new site with wowchemy theme
new_site(theme = "wowchemy/starter-academic") # type y to start site in a non-empty directory
```

# Create site

```{r}
blogdown::config_Rprofile() 
```

```{r}
blogdown::new_post(title = "Hi Hugo", 
                     ext = '.Rmarkdown', 
                     subdir = "post")
```

```{r}
blogdown::config_Rprofile() 
```

